version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    # networks:
      # innoviant_network:

  postgres_db:
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
      # innoviant_network:
  
networks:
  innoviant_network:
    driver: bridge